services:
  web:
    build: application
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./application/:/usr/src/application/
    env_file:
      - .env.dev
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    image: postgres:15-alpine
    env_file:
      - .env.dev
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data: