FROM python:3.11.4-slim-buster

WORKDIR /app

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

RUN apt-get update && apt-get install -y netcat

# copy project
COPY . /app

# install dependencies
RUN pip install --upgrade pip
# COPY ./requirements.txt /app/requirements.txt
RUN pip install -r /app/requirements.txt

RUN sed -i 's/\r$//g'  /app/entrypoint.prod.sh
RUN chmod +x  /app/entrypoint.prod.sh


# run entrypoint.prod.sh
ENTRYPOINT ["/app/entrypoint.prod.sh"]